### ISSUE TITLE
support Mini-Batch?

### ISSUE THREAD

**Issue by kangkang59812** [unlimblue/KNN_CUDA#1]

**Comment by unlimblue** [comment]
yes

**Comment by JeremyFisher** [comment]
Can I ask how would you use your KNN if you want it to use a batch?             
                                                                                
For example if I do:                                                            
                                                                                
```
import torch                                                                    
from knn_cuda import KNN                                                        
                                                                                
knn = KNN(k=1, transpose_mode=True)                                             
ref = torch.rand(32,1000, 1).cuda()                                             
query = torch.rand(32,50, 1).cuda()                                             
                                                                                
dist, indx = knn(ref, query)                                                    

```                                                                                
Then the shape of dist is:                                                      
`torch.Size([50, 1])      `                                                       
                                                                                
Which is what we want.                                                          
                                                                                
Now, what if we do:                                                             
                                                                                
```
import torch                                                                    
from knn_cuda import KNN                                                        
                                                                                
knn = KNN(k=1, transpose_mode=True)                                             
ref = torch.rand(32,1000, 1).cuda()                                             
query = torch.rand(32,50, 1).cuda()                                             
                                                                                
dist, indx = knn(ref, query)    
```                                                
                                                                                
                                                                                
Then we would like to have the dist to be of shape 32x50x1, while it is:        
torch.Size([32, 1])                                                             
                                                                                
How should we use it to get the nearest neighbours for 50 guys in every batch?

**Comment by unlimblue** [comment]
now support it, 
`pip install https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl`

**Comment by JeremyFisher** [comment]
Great! Looks like it works!

Thanks a lot @unlimblue !

**Comment by kangkang59812** [comment]
thanks. How should I do to use pytorch1.0 instead of V1.1 when installing KNN? If I use V1.1, I have to modify many codes.

**Comment by unlimblue** [comment]
If you really want to reduce trouble in the future, you'd better upgrade/modify your code to torch-1.1.0.

**Comment by Ophelia20444** [comment]
Does anyone know how to solve this problem:

Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.16.4)
Requirement already satisfied: scikit_learn in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.21.3)
Requirement already satisfied: torch>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.5/dist-packages (from scikit_learn->-r requirements.txt (line 2)) (0.14.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.5/dist-packages (from scikit_learn->-r requirements.txt (line 2)) (1.3.1)
python3 setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from knn_cuda import __version__
  File "/home/usser/KNN_CUDA/knn_cuda/__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "/home/usser/KNN_CUDA/knn_cuda/__init__.py", line 33, in load_cpp_ext
    with_cuda=True
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 971, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
makefile:6: recipe for target 'build' failed
make: *** [build] Error 1
