### ISSUE TITLE
Installation on Windows?

### ISSUE THREAD

**Issue by peichenzhong** [unlimblue/KNN_CUDA#10]
hello   i have a problem ,
 knn.o : error LNK2019: "public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)，函数 "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ) 中引用了该符号
knn.pyd : fatal error LNK1120: 1 个无法解析的外部命令
ninja: build stopped: subcommand failed.

**Comment by blukaz** [comment]
@peichenzhong take a look here: [https://github.com/blukaz/KNN_CUDA/tree/windows](url)
