### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by JeremyFisher** [unlimblue/KNN_CUDA#2]
Hey,

when I try to `from knn_cuda import KNN` I get the following error:

ImportError: (...)/KNN_CUDA/knn_cuda/csrc/_ext/knn/knn.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Any ideas how to fix that?

**Comment by unlimblue** [comment]
which torch version did you use?

**Comment by JeremyFisher** [comment]
pytorch 1.0.1 cuda90py36h8b0c50b_0

**Comment by unlimblue** [comment]
I can't reproduce it , but you can try upgrade your torch to 1.1.0 and then
```bash
pip install --upgrade https://github.com/unlimblue/KNN_CUDA/releases/download/0.1/KNN_CUDA-0.1-py3-none-any.whl
```

**Comment by JeremyFisher** [comment]
Thanks! It worked!
