### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AmnonDrory** [unlimblue/KNN_CUDA#5]
Hi, 
Thank you for this work, I think it could be very helpful for my project. When trying to install, I get the error:

  File "/home/amnon/reference/KNN_CUDA/knn_cuda/__init__.py", line 33, in load_cpp_ext
    with_cuda=True
  File "/opt/anaconda3/envs/BBR_RandLA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "/opt/anaconda3/envs/BBR_RandLA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/opt/anaconda3/envs/BBR_RandLA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1547, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/opt/anaconda3/envs/BBR_RandLA/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/envs/BBR_RandLA/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

Any idea how I can solve that?
Thanks!
Amnon

**Comment by AmnonDrory** [comment]
Checking A little deeper, I think this has something to do with the fact that I'm trying to install from inside conda. The correct libcudart,so is at /opt/anaconda3/envs/<my env>/lib. but I think that the installation is instead trying to access a version that is in /usr/local/cuda/lib64 . 
(I'm saying that because I ran grep -r cudart and found the line:
knn_cuda/csrc/_ext/knn/build.ninja:ldflags = -shared -L/opt/anaconda3/envs/BBR_RandLA_torch16/lib/python3.7/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart
).
Any idea what can be done?
Thanks,
Amnon

**Comment by AmnonDrory** [comment]
Hi, Turns out it was caused by a mismatch in versions between Cuda and Pytorch. Please feel free to delete this issue.
Thanks,
Amnon

**Comment by Jinqi-J** [comment]
Hi, I meet exactly the same problem with you, I tried to change my cuda version and torch version, but it turns out the same error, my version is cuda 11.3 torch 1.12.0 torchaudio 0.12.0 torchvision 0.13.0, could you tell me that how did you fix it?

**Comment by basteran** [comment]
> Hi, I meet exactly the same problem with you, I tried to change my cuda version and torch version, but it turns out the same error, my version is cuda 11.3 torch 1.12.0 torchaudio 0.12.0 torchvision 0.13.0, could you tell me that how did you fix it?

Same problem here, any solution?
