### ISSUE TITLE
 ImportError: cannot import name 'KNN' from 'knn_cuda'

### ISSUE THREAD

**Issue by HGamalElDiin** [unlimblue/KNN_CUDA#9]
I've installed the package by pip from the installation guide in the repo in addition to ninja,

trying the example under Usage gives this error:

ImportError: cannot import name 'KNN' from 'knn_cuda'

OS: Winidows 10
Python: 3.7

**Comment by YingZhang2561** [comment]
I've clone the branch windows. After typing 'make' or 'python setup.py install', I got the message: 
ImportError: DLL load failed while importing knn

OS: Windows 10
Python: 3.8
CUDA: 11.3
TORCH: 1.11.0
